import { useEffect, useState } from 'react';
import { Alert, Button, Card, CardContent, CircularProgress, Divider, Stack, Typography } from '@mui/material';
import { useNavigate, useParams } from 'react-router-dom';
import { api, errorMessage } from '../api';
import type { Application } from '../types';
import { StatusChip } from '../components/StatusChip';

export function ApplicationDetail() {
  const { id } = useParams(); const [app, setApp] = useState<Application | null>(null); const [error, setError] = useState(''); const navigate = useNavigate();
  useEffect(() => { void api.get(`/applications/${id}`).then((r) => setApp(r.data.data)).catch((e) => setError(errorMessage(e))); }, [id]);
  if (error) return <Alert severity="error">{error}</Alert>; if (!app) return <CircularProgress />;
  const entitlements = [app.entitledEpf && 'EPF', app.entitledEtf && 'ETF', app.entitledGovernmentPension && 'Government Pension', app.entitledOtherSocialSecurity && 'Other Social Security Scheme'].filter(Boolean).join(', ') || 'None';
  return <Stack spacing={3}><Stack direction="row" justifyContent="space-between"><div><Typography variant="h4">{app.applicationNumber ?? 'Draft application'}</Typography><Typography color="text.secondary">Application preview and history</Typography></div><StatusChip status={app.status} /></Stack>{['DRAFT', 'CORRECTION_REQUESTED'].includes(app.status) && <Button sx={{ alignSelf: 'flex-start' }} variant="contained" onClick={() => navigate(`/applicant/applications/${id}/edit`)}>Edit application</Button>}
    <Card><CardContent><Typography variant="h6">A. Applicant Information</Typography><Line label="Applicant" value={app.applicantProfile.fullName} /><Line label="NIC" value={app.applicantProfile.nic} /><Line label="Divisional Secretariat" value={app.applicantProfile.divisionalSecretariat} /><Line label="District" value={app.applicantProfile.district} /><Line label="Gender" value={app.applicantProfile.gender} /><Line label="Nationality" value={app.applicantProfile.nationality} /></CardContent></Card>
    <Card><CardContent><Typography variant="h6">B. Employment and Family Details</Typography><Line label="Tourism-sector service" value={`${app.tourismServiceYears ?? '—'} years ${app.tourismServiceMonths ?? '—'} months`} /><Line label="Currently SLTDA registered" value={app.currentlyRegisteredWithSltda ? 'Yes' : 'No'} /><Line label="SLTDA registration number" value={app.sltdaRegistrationNumber} /><Line label="Registration category" value={app.otherRegistrationCategory || app.registrationCategory} /><Line label="Current entitlements" value={entitlements} /><Line label="Family members" value={String(app.familyMembers.length)} /></CardContent></Card>
    <Card><CardContent><Typography variant="h6">C–D. Scheme, Beneficiaries and Declaration</Typography><Line label="Selected scheme" value={app.pensionScheme?.name} /><Line label="Time period" value={app.selectedSchemePeriodYears ? `${app.selectedSchemePeriodYears} year(s)` : undefined} /><Line label="Monthly contribution" value={app.monthlyContributionAmount ? `Rs. ${app.monthlyContributionAmount}` : undefined} /><Line label="Start month" value={app.contributionStartMonth?.slice(0, 7)} /><Line label="Beneficiaries" value={String(app.beneficiaries.length)} /><Line label="Applicant signature" value={app.applicantSignatureName} /><Line label="Declaration date" value={app.declarationDate?.slice(0, 10)} /><Line label="Documents" value={String(app.documents.length)} />{app.documents.map((document) => <Button key={document.id} href={`/api/documents/${document.id}/download`} size="small">Download {document.originalName}</Button>)}</CardContent></Card>
    <Card><CardContent><Typography variant="h6" sx={{ mb: 2 }}>Status history</Typography>{app.history.map((entry) => <Stack key={entry.id} direction="row" spacing={2} sx={{ py: 1.5 }}><Typography variant="body2" color="text.secondary" sx={{ minWidth: 100 }}>{new Date(entry.createdAt).toLocaleDateString()}</Typography><div><Typography fontWeight={650}>{entry.action.replaceAll('_', ' ')}</Typography><Typography variant="body2" color="text.secondary">{entry.comment || `${entry.fromStatus ?? 'NEW'} → ${entry.toStatus}`}</Typography></div></Stack>)}</CardContent></Card>
  </Stack>;
}
function Line({ label, value }: { label: string; value?: string }) { return <><Stack direction="row" justifyContent="space-between" sx={{ py: 1.2 }}><Typography color="text.secondary">{label}</Typography><Typography fontWeight={600}>{value || '—'}</Typography></Stack><Divider /></>; }
