import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Alert, Box, Button, Card, CardContent, Checkbox, CircularProgress, FormControlLabel, MenuItem, Stack, Step, StepLabel, Stepper, TextField, Typography } from '@mui/material';
import { useNavigate, useParams } from 'react-router-dom';
import { api, errorMessage } from '../api';
import type { Application } from '../types';

const steps = ['Applicant information', 'Employment details', 'Family details', 'Pension scheme', 'Beneficiaries', 'Documents', 'Declaration & preview'];
type Scheme = { id: string; name: string; code: string };
const employmentSchema = z.object({
  tourismServiceYears: z.coerce.number().int().min(0), tourismServiceMonths: z.coerce.number().int().min(0).max(11),
  currentlyRegisteredWithSltda: z.boolean(), sltdaRegistrationNumber: z.string().optional(), registrationCategory: z.string().min(1), otherRegistrationCategory: z.string().optional(),
  entitledEpf: z.boolean(), entitledEtf: z.boolean(), entitledGovernmentPension: z.boolean(), entitledOtherSocialSecurity: z.boolean(), otherSocialSecurityDetails: z.string().optional(),
});

export function ApplicationWizard() {
  const { id } = useParams(); const navigate = useNavigate(); const [app, setApp] = useState<Application | null>(null); const [schemes, setSchemes] = useState<Scheme[]>([]); const [step, setStep] = useState(0); const [error, setError] = useState('');
  const load = () => api.get(`/applications/${id}`).then((r) => setApp(r.data.data)).catch((e) => setError(errorMessage(e)));
  useEffect(() => { void load(); void api.get('/pension-schemes').then((r) => setSchemes(r.data.data)); }, [id]);
  if (!app) return error ? <Alert severity="error">{error}</Alert> : <CircularProgress />;
  const next = () => setStep((value) => Math.min(value + 1, steps.length - 1));
  return <><Typography variant="h4">Application form</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>{app.applicationNumber ?? 'Application number assigned on submission'}</Typography>
    <Stepper activeStep={step} alternativeLabel sx={{ mb: 4, display: { xs: 'none', md: 'flex' } }}>{steps.map((label) => <Step key={label}><StepLabel>{label}</StepLabel></Step>)}</Stepper>
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Card><CardContent sx={{ p: { xs: 2, md: 4 } }}>
      {step === 0 && <ApplicantInfo app={app} />}
      {step === 1 && <Employment app={app} saved={(value) => { setApp(value); next(); }} error={setError} />}
      {step === 2 && <Related title="Family details" fields={['fullName', 'relationship', 'nic', 'maritalStatus']} existing={app.familyMembers} endpoint={`/applications/${id}/family-members`} reload={load} />}
      {step === 3 && <SchemeStep app={app} schemes={schemes} saved={(value) => { setApp(value); next(); }} error={setError} />}
      {step === 4 && <Related title="Beneficiary details" fields={['fullName', 'relationship', 'nic', 'phone']} existing={app.beneficiaries} endpoint={`/applications/${id}/beneficiaries`} reload={load} />}
      {step === 5 && <Documents app={app} reload={load} />}
      {step === 6 && <Declaration app={app} updated={setApp} error={setError} />}
    </CardContent></Card><Stack direction="row" justifyContent="space-between" sx={{ mt: 3 }}><Button disabled={step === 0} onClick={() => setStep((value) => value - 1)}>Back</Button><Stack direction="row" spacing={1}><Button onClick={() => navigate(`/applicant/applications/${id}`)}>Preview</Button>{step < steps.length - 1 && step !== 1 && step !== 3 && <Button variant="contained" onClick={next}>Continue</Button>}</Stack></Stack></>;
}

function ApplicantInfo({ app }: { app: Application }) {
  const dob = new Date(app.applicantProfile.dateOfBirth); const now = new Date(); let age = now.getFullYear() - dob.getFullYear(); if (now < new Date(now.getFullYear(), dob.getMonth(), dob.getDate())) age--;
  return <><Typography variant="h5" gutterBottom>Applicant information</Typography><Info label="Full name (as per NIC)" value={app.applicantProfile.fullName} /><Info label="NIC" value={app.applicantProfile.nic} /><Info label="Date of birth" value={dob.toLocaleDateString()} /><Info label="Age (calculated)" value={String(age)} /><Info label="Gender" value={app.applicantProfile.gender} /><Info label="Nationality" value={app.applicantProfile.nationality} /><Info label="Divisional Secretariat" value={app.applicantProfile.divisionalSecretariat} /><Info label="District" value={app.applicantProfile.district} /><Info label="Contact number" value={app.applicantProfile.phone} /><Info label="Permanent address" value={app.applicantProfile.permanentAddress} /><Alert severity="info" sx={{ mt: 2 }}>Update these details on the Profile page.</Alert></>;
}
function Info({ label, value }: { label: string; value?: string }) { return <Box sx={{ py: 1.25, borderBottom: '1px solid', borderColor: 'divider' }}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography>{value || '—'}</Typography></Box>; }

function Employment({ app, saved, error }: { app: Application; saved: (a: Application) => void; error: (s: string) => void }) {
  const { register, handleSubmit, watch, formState: { isSubmitting } } = useForm({ resolver: zodResolver(employmentSchema), defaultValues: { tourismServiceYears: app.tourismServiceYears ?? 0, tourismServiceMonths: app.tourismServiceMonths ?? 0, currentlyRegisteredWithSltda: app.currentlyRegisteredWithSltda ?? false, sltdaRegistrationNumber: app.sltdaRegistrationNumber ?? '', registrationCategory: app.registrationCategory ?? '', otherRegistrationCategory: app.otherRegistrationCategory ?? '', entitledEpf: app.entitledEpf, entitledEtf: app.entitledEtf, entitledGovernmentPension: app.entitledGovernmentPension, entitledOtherSocialSecurity: app.entitledOtherSocialSecurity, otherSocialSecurityDetails: app.otherSocialSecurityDetails ?? '' } });
  return <Stack component="form" spacing={2} onSubmit={handleSubmit(async (value) => { try { saved((await api.patch(`/applications/${app.id}`, value)).data.data); } catch (e) { error(errorMessage(e)); } })}><Typography variant="h5">Employment details</Typography><Stack direction="row" spacing={2}><TextField fullWidth label="Tourism service — years" type="number" {...register('tourismServiceYears')} /><TextField fullWidth label="Months" type="number" {...register('tourismServiceMonths')} /></Stack><Alert severity="info">Five years’ tourism-industry experience is required for the SLTDA contribution. The Subject Officer records the final decision.</Alert><FormControlLabel control={<Checkbox {...register('currentlyRegisteredWithSltda')} />} label="Currently registered with SLTDA" />{watch('currentlyRegisteredWithSltda') && <TextField label="SLTDA registration number" {...register('sltdaRegistrationNumber')} />}<TextField select label="Registration category" defaultValue={app.registrationCategory ?? ''} {...register('registrationCategory')}>{[['HOMESTAY', 'Homestay'], ['BUNGALOW', 'Bungalow'], ['TOURIST_HOTEL', 'Tourist Hotels'], ['RENTED_APARTMENT', 'Rented Apartment'], ['TOURIST_GUIDE_LECTURER', 'Tourist Guide Lecturers'], ['TRAVEL_AGENT', 'Travel Agents'], ['TOURIST_DRIVER', 'Tourist Driver'], ['OTHER', 'Other Category']].map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField>{watch('registrationCategory') === 'OTHER' && <TextField label="Other category" {...register('otherRegistrationCategory')} />}<Typography fontWeight={650}>Current entitlements — tick all applicable</Typography><FormControlLabel control={<Checkbox {...register('entitledEpf')} />} label="EPF" /><FormControlLabel control={<Checkbox {...register('entitledEtf')} />} label="ETF" /><FormControlLabel control={<Checkbox {...register('entitledGovernmentPension')} />} label="Government Pension" /><FormControlLabel control={<Checkbox {...register('entitledOtherSocialSecurity')} />} label="Other Social Security Scheme" />{watch('entitledOtherSocialSecurity') && <TextField label="Other scheme details" {...register('otherSocialSecurityDetails')} />}<Alert severity="warning">The source form states these entitlement boxes must all be unchecked to qualify.</Alert><Button variant="contained" type="submit" disabled={isSubmitting}>Save and continue</Button></Stack>;
}

function SchemeStep({ app, schemes, saved, error }: { app: Application; schemes: Scheme[]; saved: (a: Application) => void; error: (s: string) => void }) {
  const [form, setForm] = useState({ pensionSchemeId: app.pensionSchemeId ?? '', selectedSchemePeriodYears: app.selectedSchemePeriodYears ?? 1, monthlyContributionAmount: app.monthlyContributionAmount ?? '', contributionStartMonth: app.contributionStartMonth?.slice(0, 7) ?? '' });
  return <Stack spacing={2}><Typography variant="h5">Pension scheme selection</Typography><Alert severity="info">Select the scheme as per Annexure 1 and attach a copy in the next step.</Alert>{!schemes.length && <Alert severity="warning">Annexure 1 was not included in the supplied document. Official schemes must be configured before submission.</Alert>}<TextField select label="Selected scheme option (Annexure 1)" value={form.pensionSchemeId} onChange={(e) => setForm({ ...form, pensionSchemeId: e.target.value })}>{schemes.map((scheme) => <MenuItem key={scheme.id} value={scheme.id}>{scheme.name} ({scheme.code})</MenuItem>)}</TextField><TextField select label="Time period" value={form.selectedSchemePeriodYears} onChange={(e) => setForm({ ...form, selectedSchemePeriodYears: Number(e.target.value) })}>{[1, 5, 10, 15].map((years) => <MenuItem key={years} value={years}>{years} Year{years > 1 ? 's' : ''}</MenuItem>)}</TextField><TextField label="Monthly contribution amount (Rs.)" type="number" value={form.monthlyContributionAmount} onChange={(e) => setForm({ ...form, monthlyContributionAmount: e.target.value })} /><TextField label="Start month" type="month" InputLabelProps={{ shrink: true }} value={form.contributionStartMonth} onChange={(e) => setForm({ ...form, contributionStartMonth: e.target.value })} /><Button variant="contained" disabled={!form.pensionSchemeId || !form.monthlyContributionAmount || !form.contributionStartMonth} onClick={async () => { try { saved((await api.patch(`/applications/${app.id}`, { ...form, monthlyContributionAmount: Number(form.monthlyContributionAmount), contributionStartMonth: `${form.contributionStartMonth}-01` })).data.data); } catch (e) { error(errorMessage(e)); } }}>Save and continue</Button></Stack>;
}

function Related({ title, fields, existing, endpoint, reload }: { title: string; fields: string[]; existing: Array<{ id: string; fullName: string; relationship: string }>; endpoint: string; reload: () => void }) {
  const [values, setValues] = useState<Record<string, string>>({}); const [error, setError] = useState(''); const labels: Record<string, string> = { fullName: 'Full name', relationship: 'Relationship', nic: title.startsWith('Beneficiary') ? 'NIC / Birth Certificate No.' : 'ID No.', maritalStatus: 'Marital status', phone: 'Contact number (if available)' };
  return <Stack spacing={2}><Typography variant="h5">{title}</Typography>{existing.map((item, index) => <Alert icon={false} severity="success" key={item.id}>{index + 1}. {item.fullName} — {item.relationship}</Alert>)}{fields.map((field) => <TextField key={field} label={labels[field]} value={values[field] ?? ''} onChange={(e) => setValues({ ...values, [field]: e.target.value })} />)}{error && <Alert severity="error">{error}</Alert>}<Button variant="outlined" disabled={!values.fullName || !values.relationship} onClick={async () => { try { await api.post(endpoint, values); setValues({}); reload(); } catch (e) { setError(errorMessage(e)); } }}>Add another</Button></Stack>;
}

function Documents({ app, reload }: { app: Application; reload: () => void }) {
  const [file, setFile] = useState<File | null>(null); const [category, setCategory] = useState('SELECTED_SCHEME_COPY'); const [error, setError] = useState('');
  return <Stack spacing={2}><Typography variant="h5">Supporting documents</Typography><Typography color="text.secondary">PDF, JPEG, or PNG; maximum 5 MB. A copy of the selected Annexure 1 scheme is required.</Typography>{app.documents.map((document) => <Alert severity="success" icon={false} key={document.id}>{document.category}: {document.originalName} ({Math.round(document.sizeBytes / 1024)} KB)</Alert>)}<TextField select label="Document category" value={category} onChange={(e) => setCategory(e.target.value)}><MenuItem value="SELECTED_SCHEME_COPY">Selected scheme copy (required)</MenuItem><MenuItem value="OTHER_SUPPORTING_DOCUMENT">Other supporting document</MenuItem></TextField><Button component="label" variant="outlined">Choose file<input hidden type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></Button>{file && <Typography variant="body2">{file.name}</Typography>}{error && <Alert severity="error">{error}</Alert>}<Button variant="contained" disabled={!file} onClick={async () => { const data = new FormData(); data.append('category', category); data.append('file', file!); try { await api.post(`/applications/${app.id}/documents`, data, { headers: { 'Content-Type': 'multipart/form-data' } }); setFile(null); reload(); } catch (e) { setError(errorMessage(e)); } }}>Upload document</Button></Stack>;
}

function Declaration({ app, updated, error }: { app: Application; updated: (a: Application) => void; error: (s: string) => void }) {
  const [form, setForm] = useState({ accepted: app.declarationAccepted, applicantSignatureName: app.applicantSignatureName ?? '', declarationDate: app.declarationDate?.slice(0, 10) ?? new Date().toISOString().slice(0, 10) }); const navigate = useNavigate();
  const payload = { declarationAccepted: form.accepted, applicantSignatureName: form.applicantSignatureName, declarationDate: form.declarationDate };
  return <Stack spacing={2}><Typography variant="h5">Declaration and submission</Typography><Alert severity="info">I have carefully read and understood the terms and conditions of the “Surekuma” Pension Scheme and willingly agree to make monthly contributions according to the selected plan. I am aware that if misconduct is found, I will not receive the SLTDA 40% contribution.</Alert><FormControlLabel control={<Checkbox checked={form.accepted} onChange={(e) => setForm({ ...form, accepted: e.target.checked })} />} label="I accept the declaration above." /><TextField label="Signature of applicant (type full name)" value={form.applicantSignatureName} onChange={(e) => setForm({ ...form, applicantSignatureName: e.target.value })} /><TextField label="Declaration date" type="date" InputLabelProps={{ shrink: true }} value={form.declarationDate} onChange={(e) => setForm({ ...form, declarationDate: e.target.value })} /><Button variant="outlined" onClick={async () => { try { updated((await api.patch(`/applications/${app.id}`, payload)).data.data); } catch (e) { error(errorMessage(e)); } }}>Save declaration</Button><Button variant="contained" size="large" disabled={!form.accepted || !form.applicantSignatureName || !form.declarationDate} onClick={async () => { try { await api.patch(`/applications/${app.id}`, payload); await api.post(`/applications/${app.id}/submit`); navigate(`/applicant/applications/${app.id}`); } catch (e) { error(errorMessage(e)); } }}>Submit application</Button></Stack>;
}
