import { useState } from 'react';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Alert, Box, Button, Card, CardContent, Container, Link, Stack, TextField, Typography } from '@mui/material';
import { Link as RouterLink, Navigate, useNavigate } from 'react-router-dom';
import { useAuth } from '../auth';
import { api, errorMessage } from '../api';

const loginSchema = z.object({ email: z.string().email(), password: z.string().min(1) });
export function LoginPage() {
  const { user, login } = useAuth(); const navigate = useNavigate(); const [error,setError]=useState('');
  const { register, handleSubmit, formState:{errors,isSubmitting} }=useForm({resolver:zodResolver(loginSchema),defaultValues:{email:'',password:''}});
  if(user) return <Navigate to={user.role==='APPLICANT'?'/applicant':user.role==='SUBJECT_OFFICER'?'/officer':'/sssb'} replace/>;
  return <AuthFrame title="Welcome back" subtitle="Sign in to continue to your Surekuma account."><Stack component="form" spacing={2} onSubmit={handleSubmit(async v=>{try{const u=await login(v.email,v.password);navigate(u.role==='APPLICANT'?'/applicant':u.role==='SUBJECT_OFFICER'?'/officer':'/sssb')}catch(e){setError(errorMessage(e))}})}>{error&&<Alert severity="error">{error}</Alert>}<TextField label="Email" {...register('email')} error={!!errors.email} helperText={errors.email?.message}/><TextField label="Password" type="password" {...register('password')} error={!!errors.password}/><Button size="large" variant="contained" type="submit" disabled={isSubmitting}>Sign in</Button><Stack direction="row" justifyContent="space-between"><Link component={RouterLink} to="/forgot-password">Forgot password?</Link><Link component={RouterLink} to="/register">Create account</Link></Stack></Stack></AuthFrame>;
}

const registerSchema=z.object({email:z.string().email(),password:z.string().min(12),fullName:z.string().min(2),nic:z.string().min(5),dateOfBirth:z.string().min(1),phone:z.string().min(7),permanentAddress:z.string().min(5)});
export function RegisterPage(){const nav=useNavigate();const [error,setError]=useState('');const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm({resolver:zodResolver(registerSchema),defaultValues:{email:'',password:'',fullName:'',nic:'',dateOfBirth:'',phone:'',permanentAddress:''}});return <AuthFrame title="Create applicant account" subtitle="Use your personal details exactly as they appear on official documents."><Stack component="form" spacing={2} onSubmit={handleSubmit(async v=>{try{await api.post('/auth/register',v);nav('/login')}catch(e){setError(errorMessage(e))}})}>{error&&<Alert severity="error">{error}</Alert>}<TextField label="Full name" {...register('fullName')} error={!!errors.fullName}/><TextField label="NIC" {...register('nic')} error={!!errors.nic}/><TextField label="Date of birth" type="date" InputLabelProps={{shrink:true}} {...register('dateOfBirth')}/><TextField label="Phone" {...register('phone')}/><TextField label="Permanent address" multiline rows={2} {...register('permanentAddress')}/><TextField label="Email" {...register('email')}/><TextField label="Password (minimum 12 characters)" type="password" {...register('password')} error={!!errors.password} helperText={errors.password?.message}/><Button variant="contained" size="large" type="submit" disabled={isSubmitting}>Register</Button><Link component={RouterLink} to="/login">Already registered? Sign in</Link></Stack></AuthFrame>}

export function ForgotPage(){const [message,setMessage]=useState('');const [email,setEmail]=useState('');return <AuthFrame title="Reset password" subtitle="We will send a time-limited reset token if your account exists."><Stack component="form" spacing={2} onSubmit={async e=>{e.preventDefault();await api.post('/auth/forgot-password',{email});setMessage('If the account exists, reset instructions have been sent.')}}>{message&&<Alert severity="success">{message}</Alert>}<TextField label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><Button variant="contained" type="submit">Send reset instructions</Button><Link component={RouterLink} to="/login">Back to sign in</Link></Stack></AuthFrame>}

function AuthFrame({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <Box sx={{minHeight:'100vh',display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'}}}><Box className="hero-pattern" sx={{display:{xs:'none',md:'flex'},color:'white',p:8,alignItems:'flex-end'}}><Box><Typography variant="overline" sx={{color:'#e1bb67'}}>Tourism Employee Social Security Fund</Typography><Typography variant="h1" sx={{fontSize:72,letterSpacing:-3}}>Surekuma</Typography><Typography sx={{maxWidth:500,opacity:.8,fontSize:18}}>A clear, secure path from application to social security membership.</Typography></Box></Box><Container maxWidth="sm" sx={{display:'flex',alignItems:'center',py:5}}><Card sx={{width:'100%'}}><CardContent sx={{p:{xs:3,sm:5}}}><Typography variant="h4" gutterBottom>{title}</Typography><Typography color="text.secondary" sx={{mb:4}}>{subtitle}</Typography>{children}</CardContent></Card></Container></Box>}

