import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, CircularProgress, Grid, Stack, Typography } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import { api, errorMessage } from '../api';
import type { ListApplication } from '../types';
import { StatusChip } from '../components/StatusChip';

export function ApplicantDashboard(){const [apps,setApps]=useState<ListApplication[]>([]);const [error,setError]=useState('');const nav=useNavigate();useEffect(()=>{api.get('/applications').then(r=>setApps(r.data.data)).catch(e=>setError(errorMessage(e)))},[]);const active=apps.filter(a=>!['COMPLETED','REJECTED'].includes(a.status));return <><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" sx={{mb:3}}><Box><Typography variant="h4">Applicant dashboard</Typography><Typography color="text.secondary">Track applications and continue outstanding work.</Typography></Box><Button variant="contained" onClick={()=>nav('/applicant/applications/new')}>Start new application</Button></Stack>{error&&<Alert severity="error">{error}</Alert>}<Grid container spacing={2} sx={{mb:4}}><Metric label="Total applications" value={apps.length}/><Metric label="In progress" value={active.length}/><Metric label="Completed" value={apps.filter(a=>a.status==='COMPLETED').length}/></Grid><Typography variant="h6" sx={{mb:2}}>Recent applications</Typography><Stack spacing={1.5}>{apps.slice(0,5).map(a=><Card key={a.id} onClick={()=>nav(`/applicant/applications/${a.id}`)} sx={{cursor:'pointer'}}><CardContent sx={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Box><Typography fontWeight={700}>{a.applicationNumber??'Draft application'}</Typography><Typography variant="body2" color="text.secondary">Updated {new Date(a.updatedAt).toLocaleDateString()}</Typography></Box><StatusChip status={a.status}/></CardContent></Card>)}{!apps.length&&!error&&<Card><CardContent><Typography color="text.secondary">No applications yet.</Typography></CardContent></Card>}</Stack></>}
function Metric({label,value}:{label:string;value:number}){return <Grid size={{xs:12,sm:4}}><Card><CardContent><Typography variant="h3" color="primary">{value}</Typography><Typography color="text.secondary">{label}</Typography></CardContent></Card></Grid>}

export function NewApplication(){const nav=useNavigate();const [busy,setBusy]=useState(false);const [error,setError]=useState('');return <Card sx={{maxWidth:720,mx:'auto'}}><CardContent sx={{p:5}}><Typography variant="h4" gutterBottom>Start a Surekuma application</Typography><Typography color="text.secondary" sx={{mb:3}}>A private draft will be created. You can save each step and return at any time.</Typography><Alert severity="warning" sx={{mb:3}}>The authoritative Word form was not supplied with this project. Verify all fields against the original form before official use.</Alert>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Button variant="contained" size="large" disabled={busy} onClick={async()=>{try{setBusy(true);const a=(await api.post('/applications')).data.data;nav(`/applicant/applications/${a.id}/edit`)}catch(e){setError(errorMessage(e));setBusy(false)}}}>{busy?<CircularProgress size={22}/>: 'Create draft and continue'}</Button></CardContent></Card>}

