import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, Stack, TextField, Typography } from '@mui/material';
import { useNavigate, useParams } from 'react-router-dom';
import { api, errorMessage } from '../api';
import type { Application, ListApplication } from '../types';
import { StatusChip } from '../components/StatusChip';

export function OfficerList({ reviewed = false }: { reviewed?: boolean }) {
  const [apps, setApps] = useState<ListApplication[]>([]); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const navigate = useNavigate();
  const load = () => api.get('/officer/applications', { params: { search, status: reviewed ? undefined : 'SUBMITTED' } }).then((r) => setApps(reviewed ? r.data.data.filter((app: ListApplication) => app.status !== 'SUBMITTED') : r.data.data)).catch((e) => setError(errorMessage(e)));
  useEffect(() => { void load(); }, [reviewed]);
  return <><Typography variant="h4">{reviewed ? 'Reviewed applications' : 'Submitted applications'}</Typography><Stack direction="row" spacing={1} sx={{ my: 3 }}><TextField size="small" label="Application no., name, or NIC" value={search} onChange={(e) => setSearch(e.target.value)} sx={{ minWidth: 320 }} /><Button variant="contained" onClick={load}>Search</Button></Stack>{error && <Alert severity="error">{error}</Alert>}<Stack spacing={1.5}>{apps.map((app) => <Card key={app.id} sx={{ cursor: 'pointer' }} onClick={() => navigate(`/officer/applications/${app.id}`)}><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={700}>{app.applicationNumber}</Typography><Typography color="text.secondary">{app.applicantProfile?.fullName} · {app.applicantProfile?.nic}</Typography></Box><StatusChip status={app.status} /></Stack></CardContent></Card>)}</Stack></>;
}
export function OfficerDashboard() { return <><Typography variant="h4" gutterBottom>Subject Officer dashboard</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Review submitted applications, assess the source-form eligibility rules, and complete the SLTDA recommendation.</Typography><OfficerList /></>; }

export function OfficerReview() {
  const { id } = useParams(); const [app, setApp] = useState<Application | null>(null); const [dialog, setDialog] = useState<'APPROVE' | 'REJECT' | 'REQUEST_CORRECTION' | null>(null); const [error, setError] = useState(''); const navigate = useNavigate();
  const load = () => api.get(`/officer/applications/${id}`).then((r) => setApp(r.data.data)).catch((e) => setError(errorMessage(e))); useEffect(() => { void load(); }, [id]);
  if (!app) return error ? <Alert severity="error">{error}</Alert> : null;
  const service = (app.tourismServiceYears ?? 0) + (app.tourismServiceMonths ?? 0) / 12; const excluded = app.entitledEpf || app.entitledEtf || app.entitledGovernmentPension || app.entitledOtherSocialSecurity; const guideline = service >= 5 && !excluded;
  return <Stack spacing={3}><Stack direction="row" justifyContent="space-between"><div><Typography variant="h4">Review {app.applicationNumber}</Typography><Typography>{app.applicantProfile.fullName} · {app.applicantProfile.nic}</Typography></div><StatusChip status={app.status} /></Stack>{app.status === 'SUBMITTED' && <Button variant="contained" sx={{ alignSelf: 'flex-start' }} onClick={async () => { await api.post(`/officer/applications/${id}/start-review`); load(); }}>Start review</Button>}
    <Alert severity={guideline ? 'success' : 'warning'}>Automated guideline: {guideline ? 'eligible' : 'not eligible'} — {app.tourismServiceYears ?? 0} years {app.tourismServiceMonths ?? 0} months’ service; excluded benefit entitlement: {excluded ? 'yes' : 'no'}. The officer records the final determination.</Alert>
    <Card><CardContent><Typography variant="h6">Application details</Typography><Detail label="Divisional Secretariat" value={app.applicantProfile.divisionalSecretariat} /><Detail label="District" value={app.applicantProfile.district} /><Detail label="SLTDA registered" value={app.currentlyRegisteredWithSltda ? 'Yes' : 'No'} /><Detail label="SLTDA registration number" value={app.sltdaRegistrationNumber} /><Detail label="Registration category" value={app.otherRegistrationCategory || app.registrationCategory} /><Detail label="Selected scheme" value={app.pensionScheme?.name} /><Detail label="Period" value={app.selectedSchemePeriodYears ? `${app.selectedSchemePeriodYears} year(s)` : undefined} /><Detail label="Monthly contribution" value={app.monthlyContributionAmount ? `Rs. ${app.monthlyContributionAmount}` : undefined} /><Detail label="Family members" value={String(app.familyMembers.length)} /><Detail label="Beneficiaries" value={String(app.beneficiaries.length)} /><Detail label="Documents" value={String(app.documents.length)} />{app.documents.map((document) => <Button key={document.id} href={`/api/documents/${document.id}/download`} size="small">Inspect {document.originalName}</Button>)}</CardContent></Card>
    {app.status === 'UNDER_REVIEW' && <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><Button color="success" variant="contained" onClick={() => setDialog('APPROVE')}>Approve and recommend</Button><Button color="warning" variant="outlined" onClick={() => setDialog('REQUEST_CORRECTION')}>Request corrections</Button><Button color="error" variant="outlined" onClick={() => setDialog('REJECT')}>Reject</Button></Stack>}
    <DecisionDialog open={dialog} guideline={guideline} close={() => setDialog(null)} submit={async (body) => { try { await api.post(`/officer/applications/${id}/decision`, body); navigate('/officer/reviewed'); } catch (e) { setError(errorMessage(e)); } }} />{error && <Alert severity="error">{error}</Alert>}
  </Stack>;
}
function Detail({ label, value }: { label: string; value?: string }) { return <Stack direction="row" justifyContent="space-between" sx={{ py: 1, borderBottom: '1px solid', borderColor: 'divider' }}><Typography color="text.secondary">{label}</Typography><Typography fontWeight={600}>{value || '—'}</Typography></Stack>; }

function DecisionDialog({ open, guideline, close, submit }: { open: 'APPROVE' | 'REJECT' | 'REQUEST_CORRECTION' | null; guideline: boolean; close: () => void; submit: (body: Record<string, unknown>) => Promise<void> }) {
  const today = new Date().toISOString().slice(0, 10); const [form, setForm] = useState({ eligible: guideline, reason: '', recommendation: '', total: '', paymentStartMonth: '', paymentMonthCount: '', paymentEndMonth: '', pensionStartMonth: '', recommendingOfficerName: '', recommendingOfficerDesignation: '', approvedOfficerSignatureName: '', approvedOfficerDesignation: '', recommendationDate: today });
  const field = (key: keyof typeof form) => ({ value: form[key], onChange: (event: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: event.target.value }) });
  const month = (value: string) => value ? `${value}-01` : undefined;
  return <Dialog open={!!open} onClose={close} fullWidth maxWidth="sm"><DialogTitle>{open?.replaceAll('_', ' ')}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><FormControlLabel control={<Checkbox checked={form.eligible} onChange={(e) => setForm({ ...form, eligible: e.target.checked })} />} label="Applicant is eligible (officer’s final decision)" /><TextField label={open === 'APPROVE' ? 'Eligibility override reason (required when decision differs from guideline)' : 'Reason (required)'} multiline rows={3} {...field('reason')} />{open === 'APPROVE' && <><TextField label="Contribution amount (monthly total)" type="number" required {...field('total')} /><TextField label="Recommendation" multiline rows={2} {...field('recommendation')} /><TextField label="Payment starting month" type="month" InputLabelProps={{ shrink: true }} required {...field('paymentStartMonth')} /><TextField label="Number of months" type="number" required {...field('paymentMonthCount')} /><TextField label="Payment end month and year" type="month" InputLabelProps={{ shrink: true }} required {...field('paymentEndMonth')} /><TextField label="Pension start month" type="month" InputLabelProps={{ shrink: true }} required {...field('pensionStartMonth')} /><TextField label="SLTDA recommending officer name" required {...field('recommendingOfficerName')} /><TextField label="Recommending officer designation" required {...field('recommendingOfficerDesignation')} /><TextField label="Signature of approved officer (type name)" required {...field('approvedOfficerSignatureName')} /><TextField label="Approved officer designation" required {...field('approvedOfficerDesignation')} /><TextField label="Recommendation date" type="date" InputLabelProps={{ shrink: true }} required {...field('recommendationDate')} /></>}</Stack></DialogContent><DialogActions><Button onClick={close}>Cancel</Button><Button variant="contained" color={open === 'REJECT' ? 'error' : 'primary'} onClick={() => submit({ decision: open, eligible: form.eligible, reason: open === 'APPROVE' ? undefined : form.reason, eligibilityOverrideReason: form.reason || undefined, recommendation: form.recommendation || undefined, approvedTotalContribution: form.total ? Number(form.total) : undefined, paymentStartMonth: month(form.paymentStartMonth), paymentMonthCount: form.paymentMonthCount ? Number(form.paymentMonthCount) : undefined, paymentEndMonth: month(form.paymentEndMonth), pensionStartMonth: month(form.pensionStartMonth), recommendingOfficerName: form.recommendingOfficerName || undefined, recommendingOfficerDesignation: form.recommendingOfficerDesignation || undefined, approvedOfficerSignatureName: form.approvedOfficerSignatureName || undefined, approvedOfficerDesignation: form.approvedOfficerDesignation || undefined, recommendationDate: form.recommendationDate || undefined })}>Confirm</Button></DialogActions></Dialog>;
}
