import { useEffect, useState } from 'react';
import { Alert, Button, Card, CardContent, Checkbox, FormControlLabel, Stack, TextField, Typography } from '@mui/material';
import { useNavigate, useParams } from 'react-router-dom';
import { api, errorMessage } from '../api';
import type { ListApplication } from '../types';
import { StatusChip } from '../components/StatusChip';

export function SssbList({ completed = false }: { completed?: boolean }) {
  const [apps, setApps] = useState<ListApplication[]>([]); const [error, setError] = useState(''); const navigate = useNavigate();
  useEffect(() => { void api.get('/sssb/applications', { params: { completed } }).then((r) => setApps(r.data.data)).catch((e) => setError(errorMessage(e))); }, [completed]);
  return <><Typography variant="h4" sx={{ mb: 1 }}>{completed ? 'Completed applications' : 'Approved applications'}</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>{completed ? 'Memberships with finished processing.' : 'Complete the Section F office-use record.'}</Typography>{error && <Alert severity="error">{error}</Alert>}<Stack spacing={1.5}>{apps.map((app) => <Card key={app.id} sx={{ cursor: 'pointer' }} onClick={() => navigate(`/sssb/applications/${app.id}`)}><CardContent><Stack direction="row" justifyContent="space-between"><div><Typography fontWeight={700}>{app.applicationNumber}</Typography><Typography color="text.secondary">{app.applicantProfile?.fullName}</Typography></div><StatusChip status={app.status} /></Stack></CardContent></Card>)}</Stack></>;
}

export function SssbProcess() {
  const { id } = useParams(); const [app, setApp] = useState<any>(null); const [error, setError] = useState(''); const navigate = useNavigate(); const today = new Date().toISOString().slice(0, 10);
  const [form, setForm] = useState({ membershipId: '', certificateNumber: '', accountOpeningDate: '', schemeRegistered: false, officerSignatureName: '', processingDate: today, officeRemarks: '' });
  const load = () => api.get(`/sssb/applications/${id}`).then((r) => setApp(r.data.data)).catch((e) => setError(errorMessage(e))); useEffect(() => { void load(); }, [id]);
  if (!app) return error ? <Alert severity="error">{error}</Alert> : null;
  return <Stack spacing={3}><Stack direction="row" justifyContent="space-between"><div><Typography variant="h4">SSSB processing</Typography><Typography>{app.applicationNumber} · {app.applicantProfile.fullName}</Typography></div><StatusChip status={app.status} /></Stack>{app.status === 'SUBJECT_OFFICER_APPROVED' && <Button variant="contained" sx={{ alignSelf: 'flex-start' }} onClick={async () => { await api.post(`/sssb/applications/${id}/start`); load(); }}>Start SSSB processing</Button>}{app.status === 'SSSB_PROCESSING' && <Card><CardContent><Stack spacing={2} component="form" onSubmit={async (event) => { event.preventDefault(); try { await api.post(`/sssb/applications/${id}/complete`, form); navigate('/sssb/completed'); } catch (e) { setError(errorMessage(e)); } }}><Typography variant="h6">F. For Office Use Only (SSSB)</Typography><TextField required label="Membership ID No." value={form.membershipId} onChange={(e) => setForm({ ...form, membershipId: e.target.value })} /><TextField required label="Certificate No." value={form.certificateNumber} onChange={(e) => setForm({ ...form, certificateNumber: e.target.value })} /><TextField required type="date" InputLabelProps={{ shrink: true }} label="Account opened on" value={form.accountOpeningDate} onChange={(e) => setForm({ ...form, accountOpeningDate: e.target.value })} /><FormControlLabel control={<Checkbox checked={form.schemeRegistered} onChange={(e) => setForm({ ...form, schemeRegistered: e.target.checked })} />} label="Scheme registered" /><TextField required label="Signature of officer (type name)" value={form.officerSignatureName} onChange={(e) => setForm({ ...form, officerSignatureName: e.target.value })} /><TextField required type="date" InputLabelProps={{ shrink: true }} label="Date" value={form.processingDate} onChange={(e) => setForm({ ...form, processingDate: e.target.value })} /><TextField label="Office remarks" multiline rows={3} value={form.officeRemarks} onChange={(e) => setForm({ ...form, officeRemarks: e.target.value })} />{error && <Alert severity="error">{error}</Alert>}<Button type="submit" variant="contained">Mark application completed</Button></Stack></CardContent></Card>}</Stack>;
}
